# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
header = """
# CHANGELOG\n
All notable changes to this project will be documented in this file.
"""
# A Tera template to be rendered for each commit in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
\n## Release
{% if version %}\
  \n### [{{ version | trim_start_matches(pat="v") }}] - ({{ timestamp | date(format="%a, %v, %T, %Z", timezone="Asia/Kuala_Lumpur") }})
{% else %}\
  \n### [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
  #### {{ group | striptags | trim }}
  {% for commit in commits | unique(attribute="message") | sort(attribute="author.timestamp") | reverse %}
    - {% if commit.id %}[{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}) {% endif %}\
      {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
      {% if commit.breaking %}[**breaking**] {% endif %}\
      {{ commit.message | split(pat="\n") | first | trim}}\
      {% if commit.remote.username %} *by @{{ commit.remote.username }}{% endif %}\
      {% if commit.remote.pr_number %} in #{{ commit.remote.pr_number }}{% endif %}\
      {% if commit.author.timestamp %} on {{ commit.author.timestamp | date(timezone="Asia/Kuala_Lumpur") }}*{% endif %}\
  {% endfor %}
{% endfor %}
---\n
## Commit Statistics\n
- {{ statistics.commit_count }} commit(s) contributed to the release.
- {{ statistics.commits_timespan | default(value=0) }} day(s) passed between the first and last commit.
- {{ statistics.conventional_commit_count }} commit(s) parsed as conventional.
- {{ statistics.links | length }} linked issue(s) detected in commits.
{%- if statistics.links | length > 0 %}
	{%- for link in statistics.links %}
    {{ "  " }}- [{{ link.text }}]({{ link.href }}) (referenced {{ link.count }} time(s))
	{%- endfor %}
{%- endif %}
{%- if statistics.days_passed_since_last_release %}
	- {{ statistics.days_passed_since_last_release }} day(s) passed between releases.
{%- endif %}\n
---\n
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
# A Tera template to be rendered at the end of the changelog.
# See https://keats.github.io/tera/docs/#introduction
footer = """
\n\ngenerated using git-cliff at {{ now() | date(format="%a, %v, %T%.3f, %Z", timezone="Asia/Kuala_Lumpur", locale="en_MY") }}
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# Render body even when there are no releases to process.
render_always = true
# An array of regex based postprocessors to modify the changelog.
postprocessors = [
  # Replace the placeholder <REPO> with a URL.
  # { pattern = 'https://github.com/HafiziRuslan/RPi-APRS', replace = "[RasPiAPRS](https://github.com/HafiziRuslan/RasPiAPRS)" },
]

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = false
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
# Require all commits to be conventional.
# Takes precedence over filter_unconventional.
require_conventional = false
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
  # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
  #{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"},
  # Check spelling of the commit message using https://github.com/crate-ci/typos.
  # If the spelling is incorrect, it will be fixed automatically.
  #{ pattern = '.*', replace_command = 'typos --write-changes -' },
  # Remove gitmoji, both actual UTF emoji and :emoji:
  { pattern = ' *(:\w+:|[\p{Emoji_Presentation}\p{Extended_Pictographic}](?:\u{FE0F})?\u{200D}?) *', replace = "" },
]
# Prevent commits that are breaking from being excluded by commit parsers.
protect_breaking_commits = false
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
  { message = "feat", group = "<!-- 0 -->ğŸš€ Features" },
  { message = "fix|Fix", group = "<!-- 1 -->ğŸ› Bug Fixes" },
  { message = "refactor|Enhance", group = "<!-- 2 -->ğŸšœ Refactor" },
  { field = "author.name", pattern = "^github", skip = true },
  { message = "doc", group = "<!-- 3 -->ğŸ“š Documentation" },
  { message = "perf", group = "<!-- 4 -->âš¡ Performance" },
  { message = "style", group = "<!-- 5 -->ğŸ¨ Styling" },
  { message = "test", group = "<!-- 6 -->ğŸ§ª Testing" },
  { message = "chore\\(release\\): prepare for", skip = true },
  { message = "chore\\(deps.*\\)", skip = true },
  { message = "chore\\(pr\\)", skip = true },
  { message = "chore\\(pull\\)", skip = true },
  { message = "chore|ci|build", group = "<!-- 7 -->âš™ï¸ Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 8 -->ğŸ›¡ï¸ Security" },
  { message = "^revert", group = "<!-- 9 -->â—€ï¸ Revert" },
  { message = ".*", group = "<!-- 10 -->ğŸ’¼ Other" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = true
# An array of link parsers for extracting external references, and turning them into URLs, using regex.
link_parsers = []
# Include only the tags that belong to the current branch.
use_branch_tags = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order releases topologically instead of chronologically.
topo_order_commits = true
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "newest"
# Process submodules commits
recurse_submodules = false
