name: 'Auto-Merge'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - auto_merge_enabled
  schedule:
    - cron: '0 9 * * mon'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@master
        with:
          time_zone: 'Asia/Kuala_Lumpur'
          require_statuses_success: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
