name: 'Auto-Merge'

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge_schedule:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@master
        with:
          time_zone: 'Asia/Kuala_Lumpur'
          require_statuses_success: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
