name: 'Release'

on:
  push:
    branches:
      - 'master'

jobs:
  pre-release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Build & test'
        run: |
          echo "done!"

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'beta'
          prerelease: true
          title: '0.1-beta-1'
          files: |
            ../../.env.SAMPLE
            ../../requirements.txt
            ../../main.py