name: 'Release'

on: push

permissions:
  contents: write

jobs:
  pre-release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          append_body: true
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'v0.1-beta.1'
          tag_name: 'beta'
          prerelease: true
          preserve_order: true
          files: |
            main.py
            requirements.txt
            default.env
