name: 'pre-release'

on:
  push:
    branches:
      - 'master'

jobs:
  pre-release:
    name: 'Pre Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Build & test'
        run: |
          echo "done!"

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'beta'
          prerelease: true
          title: 'v0.1-beta-1'
          files: |
            main.sh
            .env.SAMPLE
            requirements.txt
            main.py