name: 'Push Out Repo'

permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  release:
    types:
      - published

jobs:
  codeberg:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: 'push to Codeberg'
        uses: cssnr/mirror-repository-action@latest
        with:
          host: https://codeberg.org
          owner: hafiziruslan
          repo: RasPiAPRS
          create: false
          username: hafiziruslan
          password: ${{ secrets.CODEBERG_TOKEN }}
          summary: false
          private: false

  gitlab:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: 'push to GitLab'
        uses: cssnr/mirror-repository-action@latest
        with:
          host: https://gitlab.com
          owner: hafiziruslan
          repo: RasPiAPRS
          create: false
          username: hafiziruslan
          password: ${{ secrets.GITLAB_TOKEN }}
          summary: false
          private: false

  gitea:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: 'push to Gitea'
        uses: cssnr/mirror-repository-action@latest
        with:
          host: https://gitea.com
          owner: hafiziruslan
          repo: RasPiAPRS
          create: false
          username: hafiziruslan
          password: ${{ secrets.GITEA_TOKEN }}
          summary: false
          private: false
