name: 'Release'

on:
  workflow_run:
    workflows:
      - Auto-Merge
    types:
      - completed
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Upload default.env
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: default.env
          release_name: v0.1-beta.5
          tag: beta5
          overwrite: true
          prerelease: true
          make_latest: false

      - name: Upload requirements.txt
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: requirements.txt
          release_name: v0.1-beta.5
          tag: beta5
          overwrite: true
          prerelease: true
          make_latest: false

      - name: Upload main.sh
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.sh
          release_name: v0.1-beta.5
          tag: beta5
          overwrite: true
          prerelease: true
          make_latest: false

      - name: Upload main.py
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.py
          release_name: v0.1-beta.5
          tag: beta5
          overwrite: true
          prerelease: true
          make_latest: false
          body: "${{ github.event.head_commit.message }}\n\nby: ${{ github.event.head_commit.author.username }} on ${{ github.event.head_commit.timestamp }}"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Tag
        uses: richardsimko/update-tag@latest
        with:
          tag_name: beta5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
