name: 'Release'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'raspiaprs-0.1b6.zip'
          exclusions: '*.git* /.git* LICENSE /tests* *lock* sbom* *.md /misc*'
          recursive_exclusions: '*.md'

      - name: Upload Release
        uses: ncipollo/release-action@main
        with:
          allowUpdates: true
          artifacts: 'raspiaprs-0.1b6.zip'
          body: "${{ github.event.head_commit.message }}\n\nby: ${{ github.event.head_commit.author.username }} on ${{ github.event.head_commit.timestamp }}"
          commit: ${{ github.event.head_commit.id }}
          name: 0.1b6
          prerelease: true
          replacesArtifacts: true
          tag: beta6
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Tag
        uses: richardsimko/update-tag@latest
        with:
          tag_name: beta6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
