name: 'Release'

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Upload default.env
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: default.env
          release_name: v0.1-beta.2
          tag: beta
          overwrite: true
          prerelease: true
          make_latest: false

      - name: Upload requirements.txt
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: requirements.txt
          release_name: v0.1-beta.2
          tag: beta
          overwrite: true
          prerelease: true
          make_latest: false

      - name: Upload main.py
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.py
          release_name: v0.1-beta.2
          tag: beta
          overwrite: true
          prerelease: true
          make_latest: false
          body: ${{ github.event.head_commit.message }}

  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Generate CHANGELOG
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit CHANGELOG
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "üìù docs(changelog): update release note"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
